version: "3"
services:

  php:
    container_name: php
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./source/lg_pri_cs_center:/workspace/example-test-app
    ports:
      - "8000:8000"
      
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    ports:
      - "80:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    env_file: ./source/lg_pri_cs_center/.env

  redis:
    image: redis
    container_name: redis
    command: redis-server --port 6379
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
